### PR TITLE
Close the give tilesource, iff it can do so

### PR DESCRIPTION
**Pull request by StevenLooman**
Call `close` is called on the backend-tilesource if the TMStyle itself source is closed. Provides ability to do a proper cleanup in the tilesource used to retrieve the data from.

Without this, `tilelive-copy` will not terminate after copying if the source has any open resources, such as database connection.

### CODE REVIEW

**Comment by sethfitz** [comment]
Under what circumstances do you end up with an instance of a `tilelive-tmstyle` source that can be `close()`d?

https://github.com/mojodna/tilelive-tmstyle/blob/master/index.js#L70 always hands out a `tilelive-vector` instance, though it does instantiate another source in `toXML` that's never closed.

I suspect that the second part of your patch (`createRenderer`, etc.) is what actually addresses `tilelive-copy` not terminating. I try to avoid inline functions for clarity, so I'll take a whack at ensuring that `backend` is closed.

**Comment by sethfitz** [comment]
Have a look at #5 instead.

**Comment by StevenLooman** [comment]
I have a custom `MySQL` source, much like `mbtiles`. If I don't close this source, `tilecopy` does not terminate as the database connection is still open.

The `tilelive-vector` also doesn't properly close its source, see pull request https://github.com/mapbox/tilelive-vector/pull/120.

**Comment by sethfitz** [comment]
Does #5 address your problem then (since the part of your patch I skipped would be handled by your PR to `tilelive-vector`)?

**Comment by StevenLooman** [comment]
Just tested with my own version of tilelive-vector, as in pull request mapbox/tilelive-vector#120, #5. `tilelive-copy` does not terminate. `wtfnode` reports an open connection to `MySQL`, caused by not `close()`ing the `source`.

**Comment by sethfitz** [comment]
(You just changed my life by telling me about `wtfnode`!)

Does adding a `close` method (as in this PR) allow it to terminate?

**Comment by StevenLooman** [comment]
Yes, using the version from this PR and the version from PR https://github.com/mapbox/tilelive-vector/pull/120 makes `tile-copy` end properly.

Also, the name `wtfnode` made me chuckle at first, but it actually is really accurate. :)

**Comment by sethfitz** [comment]
Do you mind adding:

``` javascript
console.warn(new Error("close()").stack);
```

inside your `close` method so we can determine what's calling it? I'm still puzzled as to what would be holding onto an instance of TMStyle.

**Comment by StevenLooman** [comment]
`tilelive-copy` now properly quits after it is done copying, after I installed tilelive-tmstyle@0.5.0. I must have mixed up versions or something.

For completeness, the stacks of both `close()` calls:

```
Error: close()
    at TMSource.close (/home/steven/src/tiles/tilelive-mysql.js:259:18)
    at /home/steven/src/tiles/node_modules/tilelive-tmstyle/index.js:189:17
    at Query._callback (/home/steven/src/tiles/tilelive-mysql.js:175:20)
    at Query.Sequence.end (/home/steven/src/tiles/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/home/steven/src/tiles/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/home/steven/src/tiles/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/home/steven/src/tiles/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/steven/src/tiles/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/steven/src/tiles/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/steven/src/tiles/node_modules/mysql/lib/Connection.js:96:28)

Error: close()
    at TMSource.close (/home/steven/src/tiles/tilelive-mysql.js:259:18)
    at Backend.close (/home/steven/src/tiles/node_modules/tilelive-vector/backend.js:168:25)
    at Vector.close (/home/steven/src/tiles/node_modules/tilelive-vector/index.js:83:26)
    at /home/steven/src/tiles/node_modules/tilelive/lib/tilelive.js:415:17
    at pop (/home/steven/src/tiles/node_modules/tilelive/node_modules/queue-async/queue.js:24:14)
    at Object.q.defer (/home/steven/src/tiles/node_modules/tilelive/node_modules/queue-async/queue.js:55:11)
    at closingTime (/home/steven/src/tiles/node_modules/tilelive/lib/tilelive.js:414:48)
    at /home/steven/src/tiles/node_modules/tilelive/lib/tilelive.js:354:32
    at Put.done (/home/steven/src/tiles/node_modules/tilelive/lib/tilelive.js:374:17)
    at emitNone (events.js:67:13)
```

**Comment by StevenLooman** [comment]
Thank you for releasing version `0.5.0`!

**Comment by sethfitz** [comment]
Sweet!

**Pull request closed without merging**
